### ISSUE TITLE
ThirdParty components cannot use the entrypoint bridge

### ISSUE THREAD

**Issue by Burtan** [myungpyo/HiltCustomComponentSample#1]
Hi,
correct me if I'm wrong, but I'm afraid that the bridge you use to add @Inject support cannot be used with third party services that need @Provides because Hilt throws an errors on duplicate @Provide annotations and we need one for the module and one for the bridge.

**Comment by myungpyo** [comment]
Hi. Can you give me more detail about your usecase?
I'm using this pattern in the real-life multi-module project (and It's single project composed of multiple modules). 
And below is brief diagram of my multi-module project.


<img width="906" alt="Screen Shot 2022-05-24 at 9 49 45 AM" src="https://user-images.githubusercontent.com/1263179/169927126-75df9651-f050-4af8-a9c2-a8e4127796fd.png">

If your case is building data layer as an archived library project (such as AAR) and publishing it for others, this is not the same case with me. Then could give me the sample project for me?

**Comment by Burtan** [comment]
Thanks for the fast response. I missed the Bridged annotation in the bridge class. Now it works!
